# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

custom:
  tableName: 'users-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
  s3:
    host: 0.0.0.0
    port: 8001
    directory: /tmp

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  postSong:
    handler: wsgi.handler
    events:
      - http: 'POST /songs'
  getSongs:
    handler: wsgi.handler
    events:
      - http: 'GET /songs'
  downloadSong:
    handler: wsgi.handler
    events:
      - http: 'GET /songs/{song_id}'
  updateSong:
    handler: wsgi.handler
    events:
      - http: 'PUT /songs/{song_id}'
  deleteSong:
    handler: wsgi.handler
    events:
      - http: 'DELETE /songs/{song_id}'

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: songId
            AttributeType: S
        KeySchema:
          -
            AttributeName: songId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
